apiVersion: v1
kind: Service
metadata:
  name: {{.Values.gabi.instance}}-internal
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8080
    protocol: TCP
  selector:
    app: {{.Values.gabi.instance}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.gabi.instance}}-external
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: {{.Values.gabi.instance}}-tls
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: http
  selector:
    app: {{.Values.gabi.instance}}
